# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Boarding Party
email: chisel@theboardingparty.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a site for sharing information about gaming, and some of the social
  aspects around the edges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PartyBoarding
#github_username:  ""
#

socialmedia:
    twitter:        "PartyBoarding"
    github:         "chiselwright/site-theboardingparty.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-maps
  - jekyll-target-blank
  - jekyll-sitemap

google_analytics: UA-25425412-17

# https://github.com/ayastreb/jekyll-maps
# https://console.cloud.google.com/apis/credentials?folder=&organizationId=262456766053&project=theboardingparty-com
maps:
  google:
      api_key: AIzaSyBU-xgIPhAd8gIcWfMeVs_t6txMfMPBHLY

# https://jekyllrb.com/docs/permalinks/
permalink: /blog/:year/:month/:day/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
